name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up SDK 18
        uses: actions/setup-java@v2
        with:
          java-version: 18
          distribution: 'oracle'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up SDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'oracle'
          java-version: 18
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew test